### ISSUE TITLE
Can I change file content?

### ISSUE THREAD

**Issue by bubnenkoff** [rcythr/archive#8]
Is it possible to change text file content in archive without: 
extracting it
changing text
saving on disk
removing original
adding again to archive

?

**Comment by rcythr** [comment]
It's been a while since I've worked on this library, but something like the following should do what you want.

    auto zip = new ZipArchive(std.file.read("my.zip"));
    auto myFile = zip.getFile("path/to/myfile.txt");
    if(myFile !is null)
    {
        myFile.data = "This is the new file contents.";
    }
    std.file.write("my.zip", cast(ubyte[])zip.serialize());

**Comment by bubnenkoff** [comment]
Thanks!
